const express = require('express');
const path = require('path');
const userRouter = require('./routes/users');
const app = express();
app.use(express.json());
app.use('/api/v1/user', userRouter);
app.get('/home', (req, res) => { res.sendFile(path.join(__dirname, 'home.html')); });
app.use((err, req, res, next) => { console.error(err); res.status(500).send('Server Error'); });
const PORT = process.env.PORT || 8081;
app.listen(PORT, () => console.log('Web Server is listening at port ' + PORT));
